CRMSource/CRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('user/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

CRMSource/leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('',views.LeadListView.as_view(), name='lead-section'),
    # path('',views.leads_list, name='lead-section'),
    
    path('create_lead/',views.LeadCreateView.as_view(), name='create'),
    # path('create_lead/',views.lead_create, name='create'),
    
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='update'),
    # path('<int:id>/update/', views.lead_update, name='update'),
    
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
    # path('<int:id>/',views.lead_detail, name='lead-detail'),
    
    path('delete/<str:pk>/', views.LeadDeleteView.as_view(), name='delete'),
    # path('delete/<str:id>/', views.lead_delete, name='delete'),
]
 

CRMSource/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('register/', views.UserRegistrationView.as_view(), name='user-register'),
    path('login/', views.LoginUserView.as_view(), name='user-login'),
    path('logout/', views.LogoutUserView.as_view(), name='user-logout'),
    
    path('add_user/', views.ManagerUserRegistrationView.as_view(), name='user-add'),
    path("manager/", views.ManagerListView.as_view(), name="manager-section"),
    path("manager/<int:pk>/", views.ManagerListView.as_view(), name="manager-detail"),

    path('team/', views.TeamListView.as_view(), name='team-section'),
    path('create_team/', views.CreateTeamView.as_view(), name='create-team'),
    path('team/<int:pk>/', views.TeamDetailsView.as_view(), name='team-detail'),
    path('team/<int:pk>/update/', views.UpdateTeamView.as_view(), name='team-update'),
    path("team/<int:pk>/delete", views.DeleteTeamView.as_view(), name="team-delete")
    ]

CRMSource/users/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)


class Team(models.Model):
    name = models.CharField(max_length=200)
    team_lead = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    
    def __str__(self):
        return self.name
        
class TeamMember(Team):
    team_members = models.ManyToManyField(User)
    
# def post_user_created_signal(sender, instance, created, **kwargs):
#     print(instance)
#     print(created)
#     if created:
#         Team.objects.create(name="Team A", user=instance)

# post_save.connect(post_user_created_signal, sender=User)

CRMSource/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


# class UserModelForm(forms.ModelForm):
#     confirm_password = forms.CharField()
#     class Meta:
#         model = models.User
#         fields = ['username', 'email', 'password', 'confirm_password']


class UserModelForm(UserCreationForm):
    # email = forms.EmailField()
    class Meta:
        model = models.User
        fields = ['username', 'email', 'password1', 'password2']


class ManagerModelForm(forms.ModelForm):
    is_organisor = forms.BooleanField()
    is_manager = forms.BooleanField()
    class Meta:
        model = models.User
        fields = ['username', 'email', "is_organisor", 'is_manager']

class TeamModelForm(forms.ModelForm):
    # list_ = forms.ModelMultipleChoiceField(models.User.objects.all())
    class Meta:
        model = models.TeamMember
        fields = "__all__"
        
    

CRMSource/users/views.py
from django.shortcuts import render, reverse
from django.views import generic
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
from . import forms
from .mixin import OrganisorLoginRequiredMixin
from django.core.mail import send_mail

# Create your views here.


class UserRegistrationView(generic.CreateView):
    template_name = 'users/register.html'
    form_class = forms.UserModelForm
    
    def get_success_url(self):
        return reverse('user-login')


class LoginUserView(LoginView):
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse('dashboard')
    
    
class LogoutUserView(LogoutView):
    template_name = 'users/logout.html'
   

class UserDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "users/user_details.html"
    queryset = models.User.objects.all()
    context_object_name = "user"


class TeamListView(OrganisorLoginRequiredMixin, generic.ListView):
    template_name = 'team/team_list.html'
    
    def  get_queryset(self):
        team_lead = self.request.user
        return models.Team.objects.filter(team_lead=team_lead)
    
  
class ManagerUserRegistrationView(OrganisorLoginRequiredMixin, generic.CreateView):
    template_name = 'users/register.html'
    form_class = forms.ManagerModelForm  
    
    def form_valid(self, form):
        # Checking if user is a manager and setting the organisor to fault
        user_ = form.save(commit=False)
        if user_.is_manager:
            user_.is_organisor = False
        user_.save()
        
        send_mail(subject="CRM Registration Invite", 
                  message="You were add as a manager on the CRM", 
                  from_email = "gig@gig.com", 
                  recipient_list=[user_.email]
                  )
        
        return super(ManagerUserRegistrationView, self).form_valid(form) 
    
    def get_success_url(self):
        return reverse('manager-section')


class ManagerListView(OrganisorLoginRequiredMixin, generic.ListView):
    template_name = 'users/managers.html'
    context_object_name = "manager"    
   
    def get_queryset(self):

        return models.User.objects.filter(is_manager=True)
    
    
    
    
class CreateTeamView(OrganisorLoginRequiredMixin, generic.CreateView):
    template_name = 'team/create_team.html'
    form_class = forms.TeamModelForm
    
    def get_success_url(self):
        return reverse('team-section')


class TeamDetailsView(OrganisorLoginRequiredMixin, generic.DetailView):
    template_name = 'team/team_detail.html'
    context_object_name = "team"    
   
    def get_queryset(self):
        team_lead = self.request.user
        return models.Team.objects.filter(team_lead=team_lead)
    
    
class UpdateTeamView(OrganisorLoginRequiredMixin, generic.UpdateView):
    template_name = 'team/update_team.html'
    form_class = forms.TeamModelForm
    queryset = models.Team.objects.all()
        
    def get_success_url(self):
        return reverse('team-section')

class DeleteTeamView(OrganisorLoginRequiredMixin, generic.DeleteView):
    template_name = "team/delete_team.html"
    context_object_name = "team"
    
    
    def get_queryset(self):
        team_lead = self.request.user
        return models.Team.objects.filter(team_lead=team_lead)
    
    def get_success_url(self):
        return reverse('team-section')

CRMSource/users/templates/team/create_team.html
{% extends 'base.html' %}

{% block title %}
    Create Team | CRM
{% endblock title %}

{% block content %}
<h1>Create A New Team  | 
    <a href="{% url 'team-section' %}">View Teams</a> 
</h1>

<hr> 
<br>
<form method='post'>
    {% csrf_token %}
    {{form.as_p }}
    <button type='submit'>Submit</button>
</form>

<hr>



{% comment %} <a href="{% url 'leads:lead-section' %}"> Back </a> {% endcomment %}


{% endblock content %}

CRMSource/users/templates/team/delete_team.html
{% extends 'base.html' %}

{% block title %}
    Delete Team | CRM
{% endblock title %}

{% block content %}

<p>Are you sure you want to delete {{team}}?</p>

<a href="{% url 'team-detail' team.id%}">Cancel</a>


<form method="post" action="">
    {% csrf_token %}
    <button type="submit">Confirm</button>
</form>

{% endblock content %}

CRMSource/users/templates/team/team_detail.html
{% extends 'base.html' %}

{% block title %}
  Team Details | CRM
{% endblock title %}

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">TEAM DETAILS</h2>
        <h1 class="text-white text-3xl title-font font-medium mb-4">{{team.name}}</h1>

        <div class="flex mb-4">
          <a href="{% url 'team-detail' team.pk %}" class="flex-grow text-indigo-400 border-b-2 border-indigo-500 py-2 text-lg px-1">
            Over View
          </a>
          <a href="{% url 'team-update' team.pk %}" class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">
            Edit
          </a>
        </div>
        
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Team Leader</span>
          <span class="ml-auto text-white">{{team.team_lead}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Team Members</span>
          <span class="ml-auto text-white">{{team.team_members}}</span>
        </div>
        <div class="flex">

          <a href="{% url 'team-delete' team.id %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
            Delete

        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>



  {% endblock content %}

CRMSource/users/templates/team/team_list.html
{% extends 'base.html' %}
{% block title %}
    Team Section | CRM
{% endblock title %}

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
       <div class="w-full mb-4 py-6 flex justify-between items-center border-b border-gray-200">
          <div>
              <h1 class="text-white text-lg text-4xl text-gray-800">Team section</h1>
          </div>
          <div>
              <a class="text-gray-500" href="{% url 'create-team' %}"> Add New Team </a>
          </div>
       </div>
      <div class="flex flex-wrap -m-4">
        {% for team in object_list %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-800 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-gray-800 text-indigo-400 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                  <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-white text-lg title-font font-medium mb-3">
                  <a href="{% url 'team-detail' team.id  %}">{{team.name}}</a> 
                   {{team.user}}
              </h2>
              <p class="leading-relaxed text-base">
                  Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
              </p>
              <a href="{% url 'team-detail' team.id %}" class="mt-3 text-indigo-400 inline-flex items-center">
                 View Team
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="mb-2 py-4 flex-between items-center border-gray-200">
          <a class="text-gray-300" href="{% url 'create-team' %}"> Add New Team </a>
      </div>
    </div>
  </section>
  
  
  {% endblock content %}
  

CRMSource/users/templates/team/update_team.html
{% extends 'base.html' %}

{% block title %}
    Update Team | CRM
{% endblock title %}

{% block content %}
<h1>Create A New Team  | 
    <a href="{% url 'team-section' %}">View Teams</a> 
</h1>

<hr> 
<br>
<form method='post'>
    {% csrf_token %}
    {{form.as_p }}
    <button type='submit'>Submit</button>
</form>

<hr>



{% comment %} <a href="{% url 'leads:lead-section' %}"> Back </a> {% endcomment %}


{% endblock content %}