CRMSource/CRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('leads/', include('leads.urls', namespace='leads')),
    path('user/', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

CRMSource/leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('',views.LeadListView.as_view(), name='lead-section'),
    # path('',views.leads_list, name='lead-section'),
    
    path('create_lead/',views.LeadCreateView.as_view(), name='create'),
    # path('create_lead/',views.lead_create, name='create'),
    
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='update'),
    # path('<int:id>/update/', views.lead_update, name='update'),
    
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
    # path('<int:id>/',views.lead_detail, name='lead-detail'),
    
    path('delete/<str:pk>/', views.LeadDeleteView.as_view(), name='delete'),
    # path('delete/<str:id>/', views.lead_delete, name='delete'),
]
 

CRMSource/leads/models.py
from django.db import models
from users.models import User, Team


# Create your models here.

class Lead(models.Model):
    title = models.CharField(max_length = 100)
    account_name = models.CharField(max_length = 150)
    contact_name = models.CharField(max_length = 150, null=False)
    email = models.EmailField(max_length = 200)
    phone = models.CharField(max_length = 11)
    manager = models.ForeignKey(Team, null=True, blank=True, on_delete = models.SET_NULL)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    
    def __str__(self):
        return self.title
    
    
class Task(models.Model):
    PRIORITY_CHOICES = (
        ('H', 'HIGH'),
        ('M', 'MEDIUM'),
        ('L', 'LOW'),
    )
    
    TASK_TYPE = (
        ('PHONE', 'PHONE CALL'),
        ('EMAIL', 'EMAIL'),
        ('VISIT', 'VISITATION'),
        ('MEETINGS', 'MEETINGS'),
        ('PROPOSAL', 'SEND PROPOSAL'),
    )
    
    date = models.DateTimeField()
    priority = models.CharField(choices=PRIORITY_CHOICES, max_length = 100)
    task_type = models.CharField(choices=TASK_TYPE, max_length = 100)
    description = models.TextField()
    owner = models.OneToOneField(User, on_delete = models.CASCADE)
    status = models.BooleanField(default=False)
    repeat = models.BooleanField(default=False)
    action_on = models.ForeignKey(Lead, on_delete = models.CASCADE) 
    
    
    def __str__(self): 
        return self.task_type + '       ' + self.priority  
    

class Activitie(models.Model):

    ACTIVITY_TYPE = (
        ('PHONE', 'PHONE CALL'),
        ('EMAIL', 'EMAIL'),
        ('VISIT', 'VISITATION'),
        ('MEETINGS', 'MEETINGS'),
        ('PROPOSAL', 'SEND PROPOSAL'),
    )
    
    date = models.DateTimeField()
    activity_type = models.CharField(choices=ACTIVITY_TYPE, max_length = 100)
    description = models.TextField()
    # attachment = models.FileField(upload_to='')
    executor = models.ForeignKey(User, on_delete = models.CASCADE) 
    status = models.BooleanField(default=False)
    repeat = models.BooleanField(default=False)
    action_on = models.ForeignKey(Lead, on_delete = models.CASCADE) 
    
    
    def __str__(self): 
        return self.activity_type

CRMSource/leads/forms.py
from django import forms
from . import models



class LeadForm(forms.ModelForm):
    # name = forms.CharField()
    # account_name = forms.CharField()
    # contact_name = forms.CharField()
    # email = forms.EmailField()
    # phone = forms.CharField()
   
    class Meta:
        model = models.Lead
        fields = [
            "title",
            "account_name",
            "contact_name",
            "email",
            "phone",
            "manager"
        ]

CRMSource/leads/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import  LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from . models import Lead
from .forms import LeadForm
from users.mixin import OrganisorLoginRequiredMixin
# Create your views here.



"""
    Class based views are views that performs specify task.
    And they follow CRUD+L = create read/retrieve, update, delete and list
    To use the class based views in the urls path add the method ClassViewName.as_view()
    when working with class based views the context which is not given by me, is by default set to object_list.
    Or to use your own name set the context_object_name to your varible
    
    The class view is above why the function based is below.
"""

class LeadListView(LoginRequiredMixin, ListView):
    template_name = 'leads/lead_section.html'
    context_object_name = "leads"
    
    def get_queryset(self):
        user = self.request.user
        queryset = Lead.objects.all()
            
        if user.is_manager:
            queryset = queryset.filter(manager__team_lead=self.request.user)
        return queryset


# def leads_list(request):
#     leads = Lead.objects.all()
#     context = {
#         'leads': leads,
#     }
#     return render(request, 'leads/lead_section.html', context)


class LeadDetailView(LoginRequiredMixin, DetailView):
    template_name = 'leads/lead_details.html'
    context_object_name = "lead"
    
    def get_queryset(self):
        user = self.request.user
        queryset = Lead.objects.all()
            
        if user.is_manager:
            queryset = queryset.filter(manager__team_lead=self.request.user)
        return queryset
    
# def lead_detail(request, id):
#     lead = Lead.objects.get(id=id)
    
#     context = {
#         'lead': lead,
#     }
#     return render(request, 'leads/lead_details.html', context)


class LeadCreateView(OrganisorLoginRequiredMixin, CreateView):
    template_name = 'leads/create_lead.html'
    form_class = LeadForm
    
    def get_success_url(self):
        return reverse("leads:lead-section")
    
    def form_valid(self, form):
        # Setting the lead owner to the loggedin user
        lead_owner = form.save(commit=False)
        lead_owner.owner = self.request.user
        lead_owner.save()
        
        # TO send Mail
        send_mail(
            subject = "A lead Has Been Created",
            message = "Go To The Site To See The Lead",
            from_email = "test@test.com",
            recipient_list = ["test2@test.com"]
        )
        
        return super(LeadCreateView, self).form_valid(form)
    

# def lead_create(request):
#     form = LeadForm()
    
#     if request.method == 'POST':
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/leads')
    
#     context = {
#         'form': form
#     }
#     return render(request, "leads/create_lead.html", context)


class LeadUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'leads/update_lead.html'
    form_class = LeadForm
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(manager__team_lead=self.request.user)
    
    
    def get_success_url(self):
        return reverse("leads:lead-section")


# def lead_update(request, id):
    
#     lead = Lead.objects.get(id=id)
#     form = LeadForm(instance=lead)
    
#     if request.method == 'POST':
#         form = LeadForm(request.POST, instance=lead)
#         if form.is_valid():
#             form.save()
#             return redirect('/leads')
        
#     context = {
#         'lead': lead,
#         'form': form,
#     }
#     template_name = 'leads/update_lead.html'
#     return render( request, template_name, context)


class LeadDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'leads/delete_lead.html'
    
    context_object_name = 'item'

    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(manager__team_lead=self.request.user)
    
    
    def get_success_url(self):
        return reverse("leads:lead-section")


# def lead_delete(request, id):
#     lead = Lead.objects.get(id=id)
#     if request.POST:
#         lead.delete()
#         return redirect('/leads')
    
#     context = {
#         'item':lead
#     }
#     return render(request, 'leads/delete_lead.html', context)

CRMSource/leads/templates/leads/create_lead.html
{% extends 'base.html' %}

{% block title %}
    Create Lead | CRM
{% endblock title %}

{% block content %}
<h1>Create A New Lead</h1>
<hr> 
<br>
<form method='post'>
    {% csrf_token %}
    {{form.as_p }}
    <button type='submit'>Submit</button>
</form>

<hr>



{% comment %} <a href="{% url 'leads:lead-section' %}"> Back </a> {% endcomment %}


{% endblock content %}

CRMSource/leads/templates/leads/delete_lead.html
{% extends 'base.html' %}

{% block title %}
    Delete Lead | CRM
{% endblock title %}

{% block content %}

<p>Are you sure you want to delete {{item}}?</p>

<a href="{% url 'leads:lead-detail' item.id%}">Cancel</a>


<form method="post" action="">
    {% csrf_token %}
    <button type="submit">Confirm</button>
</form>

{% endblock content %}

CRMSource/leads/templates/leads/lead_details.html
{% extends 'base.html' %}

{% block title %}
  Lead Details | CRM
{% endblock title %}

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD DETAILS</h2>
        <h1 class="text-white text-3xl title-font font-medium mb-4">{{lead.title}}</h1>

        <div class="flex mb-4">
          <a class="flex-grow text-indigo-400 border-b-2 border-indigo-500 py-2 text-lg px-1">
            Over View
          </a>
          <a href={% url 'leads:update' lead.id %} class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">
            Edit
          </a>
        </div>
        
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Account Name</span>
          <span class="ml-auto text-white">{{lead.account_name}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Contact Person</span>
          <span class="ml-auto text-white">{{lead.contact_name}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Manager</span>
          <span class="ml-auto text-white">{{lead.manager}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Phone No</span>
          <span class="ml-auto text-white">{{lead.phone}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-800 py-2">
          <span class="text-gray-500">Owner</span>
          <span class="ml-auto text-white">{{lead.owner}}</span>
        </div>
        <div class="flex">

          <a href="{% url 'leads:delete' lead.id %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
            Delete
          </a>
          {% comment %} <a href="{% url 'leads:lead-section' %}" class="rounded-full w-10 h-10 bg-gray-800 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
          Back
          </a> {% endcomment %}
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>










  {% comment %} <h1>Lead Details</h1>

  <h5> Lead Account's Name : {{lead.account_name}}</h5>
  <h5> Lead Contact's Name : {{lead.contact_name}}</h5>
  
  <hr>
  
  <div class="lead">
    <h5> {{lead.title}} {{lead.account_name}}  {{lead.contact_name}}  {{lead.phone}} </h5> 
    <br>
      <a class="btn btn-sm btn-info" href="{% url 'leads:update' lead.id %}">Update</a> 
      <a class="btn btn-sm btn-danger" href="{% url 'leads:delete' lead.id %}">Delete</a>
  </div>
  
  <hr> 
  <br>
  <a href="{% url 'leads:lead-section' %}"> Back </a> {% endcomment %}

  {% endblock content %}

CRMSource/leads/templates/leads/lead_section.html
{% extends 'base.html' %}
{% block title %}
    Lead Section | CRM
{% endblock title %}

{% block content %}



<section class="text-gray-400 bg-gray-900 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
     <div class="w-full mb-4 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-white text-lg text-4xl text-gray-800">Leads section</h1>
        </div>
        {% if request.user.is_organisor %}
        <div>
          <a class="text-gray-500" href="{% url 'leads:create' %}"> Add New Lead </a>
        </div>
        {% endif %}
     </div>
    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-800 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-gray-800 text-indigo-400 flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-white text-lg title-font font-medium mb-3">
                <a href="{% url 'leads:lead-detail' lead.id %}">{{lead.title}}</a>  {{lead.account_name}}  {{lead.contact_name}}  {{lead.phone}}
            </h2>
            <p class="leading-relaxed text-base">
                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a href="{% url 'leads:lead-detail' lead.id %}" class="mt-3 text-indigo-400 inline-flex items-center">
               View Lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% if request.user.is_organisor %}
    <div class="mb-2 py-4 flex-between items-center border-gray-200">
      <a class="text-gray-300" href="{% url 'leads:create' %}"> Add New Lead </a>
    </div>
    {% endif %}

  </div>
</section>


{% endblock content %}

CRMSource/leads/templates/leads/update_lead.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD DETAILS</h2>
          <h1 class="text-white text-3xl title-font font-medium mb-4">{{lead.title}}</h1>

          <div class="flex mb-4">
            <a href={% url 'leads:lead-detail' lead.id %} class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">
                Over View
            </a>
            <a href={% url 'leads:update' lead.id %} class="flex-grow text-indigo-400 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Edit
            </a>
          </div>
          
          <form method='post'>
            {% csrf_token %}
            {{form.as_p }}
            <button type='submit'>Submit</button>
        </form>
        
          <div class="flex">
  
            <a href="{% url 'leads:delete' lead.id %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
              Delete
            </a>
            {% comment %} <a href="{% url 'leads:lead-section' %}" class="rounded-full w-10 h-10 bg-gray-800 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            Back
            </a> {% endcomment %}
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>







{% comment %} <h1>Update Lead: {{lead.title}}</h1>
<hr> 
<br>
<form method='post'>
    {% csrf_token %}
    {{form.as_p }}
    <button type='submit'>Submit</button>
</form>

<hr>



<a href="{% url 'leads:lead-detail' lead.id %}"> Back </a> {% endcomment %}

{% endblock content %}